---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    provisioners:
      - {type: hosts}
      - {type: shell, path: scripts/provision.sh}
      - {type: pe_bootstrap, role: !ruby/sym master}
      - {type: shell, inline: '/opt/puppet/bin/puppet module install zack/r10k --modulepath /opt/puppet/share/puppet/modules'}
      - {type: shell, inline: '/opt/puppet/bin/puppet module install hunner/hiera --modulepath /opt/puppet/share/puppet/modules'}
      - {type: puppet, manifest_file: bootstrap.pp}
      - {type: shell, inline: 'rm -rf /var/cache/r10k/-vagrant; r10k deploy env -p'}
  pe-agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
    provisioners:
      - {type: hosts}
      - {type: shell, path: scripts/provision.sh}
      - {type: pe_bootstrap}
      - {type: shell, path: scripts/safe_puppet.sh}
